@port = 3000
@server = http://localhost:{{port}}
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2VAbWFpbC5jb20iLCJzdWIiOnsibmFtZSI6IkpvaG4gRG9lIn0sImlhdCI6MTcyODU5MjE5NywiZXhwIjoxNzI4NjEwMTk3fQ.zpPJy3ntP0tPka-jj9QO6ftErDs6yNQTt03d5vwdEwQ


### WHOAMI
GET {{server}}/users/4f89e909-3c4d-4737-a073-160cdac372f2
Content-Type: application/json
Authorization: Bearer {{access_token}}



### FIND ALL USERS
GET {{server}}/users/all
Content-Type: application/json
