@port = 3000
@server = http://localhost:{{port}}
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2VAbWFpbC5jb20iLCJzdWIiOnsibmFtZSI6IkpvaG4gRG9lIn0sImlhdCI6MTcyODU4ODk1MCwiZXhwIjoxNzI5MTkzNzUwfQ._pw600NmzxCkDCDVgvdPQHmuCjLL5VmPqgmvMhtUfX4

### SIGN-IN
POST {{server}}/auth/sign-in
Content-Type: application/json

{ 
    "username": "johndoe@mail.com",
    "password": "12345678"
}

### SIGN-IN
POST {{server}}/auth/refresh-token
Content-Type: application/json
Authorization: Refresh {{refresh_token}}
